CREATE USER Server1 IDENTIFIED BY "password";
GRANT CONNECT TO Server1;
GRANT CONNECT, RESOURCE, DBA TO Server1;

CREATE USER Server2 IDENTIFIED BY "password";
GRANT CONNECT TO Server2;
GRANT CONNECT, RESOURCE, DBA TO Server2;

CREATE USER Server3 IDENTIFIED BY "password";
GRANT CONNECT TO Server3;
GRANT CONNECT, RESOURCE, DBA TO Server3;